### ISSUE TITLE
Unable to start socket service after packaging

### ISSUE THREAD

**Issue by umeitime** [Heit/netty-socketio-spring#2]
Downloading code, using compiler tools to start is normal, but after the war package is booting, the socket service is not activated.

**Comment by Heit** [comment]
Hello.
Do you use external container for deployment? If not, everything should be ok.
If you use external container there is maybe dependency conflict. You have to mark dependencies provided by a container.

**Comment by umeitime** [comment]
Yes, you are right.I was deployed on an external Tomcat container.Tanks!

**Comment by Heit** [comment]
Solved.
